

export const CONTACT_SUCCESS = 'CONTACT_SUCCESS'
export const CONTACT_PROCESSING = 'CONTACT_PROCESSING'
export const CONTACT_FAILED = 'CONTACT_FAILED'

export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS'